name = "hono_medium"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzVmNTA3M2EtYTYzYS00NjZmLThlYmItZjEzMjA3ODFkYWJmIiwidGVuYW50X2lkIjoiYWFkMjFiZmZkZDU0NDJiNjI4MTc5OTEwNjAxODA2NzQwYTM0YWJiMWU5ZjIwNWViOGFkZDU3YWVlMTU0ODU4NiIsImludGVybmFsX3NlY3JldCI6IjFiZWEwNTZmLWVkYTctNDcyNi1hOWIyLTNiYzU0YjkzYjQwYSJ9.ACOEzDzrbuV8oGfE9O61pzCJpTfxPNvgVXK7ds3T12s"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
